TARGET = miniconv.cjk
OBJS = main.o miniconv.o

BUILD_PRX=1
PRX_EXPORTS=miniconvexp.exp

USE_PSPSDK_LIBC=1

INCDIR =
CFLAGS = -O2 -G0 -Wall -DGBK_CONV -DBIG5_CONV -DSJIS_CONV -DEUC_KR_CONV
CXXFLAGS = $(CFLAGS) -fno-exceptions -fno-rtti
ASFLAGS = $(CFLAGS)

LIBDIR =
LIBS =
LDFLAGS = -mno-crt0 -nostartfiles

PSPSDK=$(shell psp-config --pspsdk-path)
include $(PSPSDK)/lib/build.mak
