TARGET = miniconv.eur
OBJS = main.o miniconv.o

BUILD_PRX=1
PRX_EXPORTS=miniconvexp.exp

USE_PSPSDK_LIBC=1

INCDIR =
CFLAGS = -O2 -G0 -Wall -DMS_EE_CONV -DMS_CYRL_CONV -DISO8859_1_CONV -DISO8859_2_CONV
CXXFLAGS = $(CFLAGS) -fno-exceptions -fno-rtti
ASFLAGS = $(CFLAGS)

LIBDIR =
LIBS =
LDFLAGS = -mno-crt0 -nostartfiles

PSPSDK=$(shell psp-config --pspsdk-path)
include $(PSPSDK)/lib/build.mak
